[package]
name = "showtimes-fs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "File storage handler for Showtimes API"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
s3-tokio.workspace = true
chrono.workspace = true
tosho-macros = "0.3"
futures = "0.3.30"
bytes = "1"
mime_guess = "2.0.5"
