[package]
name = "showtimes-fs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "File storage handler for Showtimes API"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
chrono.workspace = true
futures-util.workspace = true
tosho-macros.workspace = true
tracing.workspace = true

mime_guess.workspace = true
rusty-s3.workspace = true
reqwest.workspace = true
